### ISSUE TITLE
cryptography setup command: Invalid environment marker: python_version < '3'

### ISSUE THREAD

**Issue by ashutoshsingh1** [fim/flask-ask-docker#1]
Hi Serafeim Mellos,
Thanks for creating this repo which helps me a lot to learn "How I can setup docker for Alexa skills".
I am new in docker. I just clone your code and try to follow your instruction and while docker building I am getting following error.

Downloading/unpacking flask-ask
  Downloading Flask_Ask-0.9.7-py2.py3-none-any.whl
Downloading/unpacking Flask==0.12.1 (from flask-ask)
Downloading/unpacking PyYAML==3.12 (from flask-ask)
  Running setup.py (path:/tmp/pip_build_root/PyYAML/setup.py) egg_info for package PyYAML
    
Downloading/unpacking six==1.10.0 (from flask-ask)
  Downloading six-1.10.0-py2.py3-none-any.whl
Downloading/unpacking aniso8601==1.2.0 (from flask-ask)
  Running setup.py (path:/tmp/pip_build_root/aniso8601/setup.py) egg_info for package aniso8601
    
Downloading/unpacking pyOpenSSL==17.0.0 (from flask-ask)
Downloading/unpacking Jinja2>=2.4 (from Flask==0.12.1->flask-ask)
Downloading/unpacking Werkzeug>=0.7 (from Flask==0.12.1->flask-ask)
Downloading/unpacking itsdangerous>=0.21 (from Flask==0.12.1->flask-ask)
  Running setup.py (path:/tmp/pip_build_root/itsdangerous/setup.py) egg_info for package itsdangerous
    
    warning: no previously-included files matching '*' found under directory 'docs/_build'
Downloading/unpacking click>=2.0 (from Flask==0.12.1->flask-ask)
Downloading/unpacking python-dateutil (from aniso8601==1.2.0->flask-ask)
Downloading/unpacking cryptography>=1.7 (from pyOpenSSL==17.0.0->flask-ask)
  Running setup.py (path:/tmp/pip_build_root/cryptography/setup.py) egg_info for package cryptography
    error in cryptography setup command: Invalid environment marker: python_version < '3'
    Complete output from command python setup.py egg_info:
    error in cryptography setup command: Invalid environment marker: python_version < '3'
---------------------------------------------------------------------------------------------------------------------------

**Comment by ashutoshsingh1** [comment]
Hi,
 I just upgraded pip and setuptools and it solved my issue

RUN pip install --upgrade pip
RUN pip install --upgrade setuptools

**Comment by fim** [comment]
Glad to see you got your issue resolved. Thanks for the update as well!
